### ISSUE TITLE
Submission Examples

### ISSUE THREAD

**Issue by jgazlyEng** [Puppetworks-Animation-Studio/deadline-davinci-resolve#2] opened 2020-10-29 21:59 UTC
Having issues getting this to work, Could you post an example job_info.job file along with an example command please?
OS: Windows 10 Enterprise

I've moved the DaVinciResolve folder in to our custom\plugins folder

I've created a job_info.job file with the following info:
Plugin=DaVinciResolve
ProjectName=renderTest-deadline-resolve
OutputPath=

I'm running the following:
deadlinecommand.exe C:\Users<username>\dev\job_info.job

I'm getting the following error:
Deadline Command 10.1 [v10.1.9.2 Release (3d6a64d94)]
Error: could not find job info file: Plugin=DaVinciResolve (Deadline.Submission.DeadlineSubmissionException)

**Comment by asztalosdani** [comment] 2020-11-05 13:05
Closing this as it is a duplicate of #1

**Closed as completed by asztalosdani** 2020-11-05 13:05 UTC
